name:
  SCHEDULE
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: 
jobs:
  java-script-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 8.0.352+8
          distribution: adopt
      - run: java src/java/Demo.java
  
