name:
  SCHEDULE
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: 
jobs:
  java-script-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - run: mvn -B clean package -f pom.xml
      - run: java -cp ./target/schedule-1.0-SNAPSHOT.jar Demo
  
